### ISSUE TITLE
{"status":500,"reason":"Cannot read properties of undefined (reading 'tier')"}

### ISSUE THREAD

**Issue by ghost** [Altpapier/SkyHelperAPI#17]
v1/profiles/ was the endpoint :(

**Comment by ghost** [comment]
24|Skyhelp | TypeError: Cannot read properties of undefined (reading 'tier')
24|Skyhelp |     at getPets (/root/SkyHelperAPI/stats/pets.js:166:75)
24|Skyhelp |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
24|Skyhelp |     at async Promise.all (index 7)
24|Skyhelp |     at async parseProfile (/root/SkyHelperAPI/utils/hypixel.js:222:115)
24|Skyhelp |     at async /root/SkyHelperAPI/routes/v1/profiles.js:19:21
